# THIS MODULE HANDLES THE DATABASE CONNECTION USING SQLALCHEMY
# IT CREATES AN ENGINE THAT OTHER MODULES USE TO RUN SQL QUERIES
import os
from sqlalchemy import create_engine

DATABASE_FINANCE = os.getenv("DATABASE_FINANCE")
engine = create_engine(DATABASE_FINANCE, future=True)